# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_7Z "")
SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_IFW "")
SET(CPACK_BINARY_NSIS "")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TXZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_CMAKE_GENERATOR "Visual Studio 14 2015 Win64")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_GENERATOR "STGZ;TGZ;TBZ2;ZIP")
SET(CPACK_INSTALL_CMAKE_PROJECTS "D:/repos/fluidsynth_windows/fluidsynth-1.1.6/buildit;FluidSynth;ALL;/")
SET(CPACK_INSTALL_PREFIX "C:/Program Files/FluidSynth")
SET(CPACK_MODULE_PATH "D:/repos/fluidsynth_windows/fluidsynth-1.1.6/cmake_admin")
SET(CPACK_NSIS_DISPLAY_NAME "fluidsynth 1.1.6")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
SET(CPACK_NSIS_PACKAGE_NAME "fluidsynth 1.1.6")
SET(CPACK_OUTPUT_CONFIG_FILE "D:/repos/fluidsynth_windows/fluidsynth-1.1.6/buildit/CPackConfig.cmake")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "D:/repos/fluidsynth_windows/fluidsynth-1.1.6/README")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "FluidSynth real-time synthesizer")
SET(CPACK_PACKAGE_EXECUTABLES "fluidsynth;FluidSynth CLI")
SET(CPACK_PACKAGE_FILE_NAME "fluidsynth-1.1.6-win64")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "fluidsynth 1.1.6")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "fluidsynth 1.1.6")
SET(CPACK_PACKAGE_NAME "fluidsynth")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "fluidsynth.org")
SET(CPACK_PACKAGE_VERSION "1.1.6")
SET(CPACK_PACKAGE_VERSION_MAJOR "1")
SET(CPACK_PACKAGE_VERSION_MINOR "1")
SET(CPACK_PACKAGE_VERSION_PATCH "6")
SET(CPACK_RESOURCE_FILE_LICENSE "D:/repos/fluidsynth_windows/fluidsynth-1.1.6/COPYING")
SET(CPACK_RESOURCE_FILE_README "C:/Program Files (x86)/CMake/share/cmake-3.5/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "C:/Program Files (x86)/CMake/share/cmake-3.5/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_7Z "")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "TGZ;TBZ2;ZIP")
SET(CPACK_SOURCE_IGNORE_FILES "/.svn/;/build/;~$;.cproject;.project;/.settings/;")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "D:/repos/fluidsynth_windows/fluidsynth-1.1.6/buildit/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "fluidsynth-1.1.6")
SET(CPACK_SOURCE_STRIP_FILES "OFF")
SET(CPACK_SOURCE_TBZ2 "")
SET(CPACK_SOURCE_TGZ "")
SET(CPACK_SOURCE_TXZ "")
SET(CPACK_SOURCE_TZ "")
SET(CPACK_SOURCE_ZIP "")
SET(CPACK_STRIP_FILES "ON")
SET(CPACK_SYSTEM_NAME "win64")
SET(CPACK_TOPLEVEL_TAG "win64")
SET(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "D:/repos/fluidsynth_windows/fluidsynth-1.1.6/buildit/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
